// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7pSqgxkX5LK-RAzomAmLeeGa2ng5TMGo',
    appId: '1:447871875146:web:49b820dda8976f5b4a4eb3',
    messagingSenderId: '447871875146',
    projectId: 'task-management-1e2b9',
    authDomain: 'task-management-1e2b9.firebaseapp.com',
    storageBucket: 'task-management-1e2b9.firebasestorage.app',
    measurementId: 'G-L8QC3NLGXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7LnjA-Va9_0n__07jLy3nTV12dWOHhGo',
    appId: '1:447871875146:android:ea5e79ba940d24814a4eb3',
    messagingSenderId: '447871875146',
    projectId: 'task-management-1e2b9',
    storageBucket: 'task-management-1e2b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-wlcGwPyAn_jEjUwqsvkOi5u0nLYrv70',
    appId: '1:447871875146:ios:5253048d3092b0964a4eb3',
    messagingSenderId: '447871875146',
    projectId: 'task-management-1e2b9',
    storageBucket: 'task-management-1e2b9.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-wlcGwPyAn_jEjUwqsvkOi5u0nLYrv70',
    appId: '1:447871875146:ios:5253048d3092b0964a4eb3',
    messagingSenderId: '447871875146',
    projectId: 'task-management-1e2b9',
    storageBucket: 'task-management-1e2b9.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7pSqgxkX5LK-RAzomAmLeeGa2ng5TMGo',
    appId: '1:447871875146:web:a2ff3460b772cf2b4a4eb3',
    messagingSenderId: '447871875146',
    projectId: 'task-management-1e2b9',
    authDomain: 'task-management-1e2b9.firebaseapp.com',
    storageBucket: 'task-management-1e2b9.firebasestorage.app',
    measurementId: 'G-JKH3P8JVS8',
  );

}